<?php

$postcard_array = array(
	1 => array(
		"photo" => "arborlakes_courtyard",
		"caption" => "Arbor Lakes Courtyard"),
	2 => array(
		"photo" => "arborlakes_sculpture",
		"caption" => "Arbor Lakes Sculpture"),
	3 => array(
		"photo" => "arborlakes_trees",
		"caption" => "Arbor Lakes Pond"),
	4 => array(
		"photo" => "arborlakes_fall",
		"caption" => "Arbor Lakes in the Fall"),
	5 => array(
		"photo" => "arborlakes_fall_pond",
		"caption" => "Arbor Lakes Pond in the Fall"),
	6 => array(
		"photo" => "arborlakes_snow",
		"caption" => "Arbor Lakes in the Winter"),
	7 => array(
		"photo" => "um_football",
		"caption" => "U-M Football",
		"copyright" => "U-M Photo Services"),
	8 => array(
		"photo" => "um_stadium",
		"caption" => "U-M Stadium",
		"copyright" => "U-M Photo Services"),
	9 => array(
		"photo" => "ulrichs",
		"caption" => "Ulrich's Books on South U"),
	10 => array(
		"photo" => "burton_tower",
		"caption" => "Burton Tower"),
	11 => array(
		"photo" => "burton_tower_flag",
		"caption" => "The Flag over Burton Tower and Rackham",
		"copyright" => "U-M Photo Services"),
	12 => array(
		"photo" => "rackham",
		"caption" => "Rackham Graduate School",
		"copyright" => "U-M Photo Services"),
	13=> array(
		"photo" => "winter_snow",
		"caption" => "Kelsey Museum in Winter Snow",
		"copyright" => "U-M Photo Services"),
	14=> array(
		"photo" => "north_campus",
		"caption" => "Engineering College on North Campus",
		"copyright" => "U-M Photo Services"),
	15 => array(
		"photo" => "golf_course",
		"caption" => "U-M Golf Course",
		"copyright" => "U-M Photo Services"),
	16 => array(
		"photo" => "angell_hall",
		"caption" => "Angell Hall"),
	17 => array(
		"photo" => "michigan_union",
		"caption" => "Michigan Union"),
	18 => array(
		"photo" => "diag_m",
		"caption" => "The Diag"),
	19 => array(
		"photo" => "umma",
		"caption" => "U-M Museum of Art"),
	20 => array(
		"photo" => "rackham_doors_sunset",
		"caption" => "Rackham Doors at Sunset"),
	21 => array(
		"photo" => "law_school_cloisters",
		"caption" => "Law School Cloisters"),
	22 => array(
		"photo" => "music_school_pond",
		"caption" => "Music School Pond"),
	23 => array(
		"photo" => "museum_puma",
		"caption" => "Puma outside the Exhibit Museum of Natural History"),
	24 => array(
		"photo" => "cube",
		"caption" => "The Rosenthal Cube"),
	25 => array(
		"photo" => "peace_corps",
		"caption" => "John F. Kennedy Peace Corps plaque at the Michigan Union")
);

$current_postcards = array(2, 3, 5, 7, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25);

?>